#! /bin/bash
docker stop databasecourse
docker rm databasecourse -f
docker image rm databasecourse -f
docker build . -t databasecourse --no-cache --progress=plain
# docker build . -t databasecourse --no-cache