#! /bin/bash

#docker stop databasecourse
docker run -p 7474:7474 -p 7687:7687 -p 27017:27017 -p 6379:6379 -t -d -h dbCourseUbuntu --name databasecourse databasecourse
docker start databasecourse
echo ""
echo "###"
echo "STARTING DOCKER CONTAINER FOR THE DATABASE COURSE"
echo "# Read the file help.txt to view all the available database systems and commands to use them"
echo "# Run command 'exit' to get out of the Docker container."
echo "###"
echo ""
docker exec -it databasecourse /bin/bash
